const ADD_POST = 'ADD-POST';
const ADD_MESSAGE = 'ADD-MESSAGE';
const UPDATE_NEW_POST_TEXT = 'UPDATE_NEW_POST_TEXT';
const UPDATE_NEW_MESSAGE_BODY = 'UPDATE_NEW_MESSAGE_BODY';
const TOGGLE_POST_LIKE = 'TOGGLE_POST_LIKE';
const FOLLOW = 'FOLLOW';
const UNFOLLOW = 'UNFOLLOW';
const SET_USERS = 'SET_USERS';
const SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT';
const SET_CURRENT_PAGE = 'SET_CURRENT_PAGE';
const SET_FETCHING_STATE = 'SET_FETCHING_STATE';
const SET_USER_PROFILE = 'SET_USER_PROFILE';
const SET_PROFILE_FETCHING_STATE = 'SET_PROFILE_FETCHING_STATE';
const TOGGLE_IS_FOLLOWING_PROGRESS = 'TOGGLE_IS_FOLLOWING_PROGRESS';
const SET_STATUS = 'SET_STATUS';
const SET_PROFILE_PHOTO = 'SET_PROFILE_PHOTO';
const SET_PROFILE_DATA = 'SET_PROFILE_DATA';

/* eslint import/no-anonymous-default-export: [2, {"allowObject": true}] */
export default {
  ADD_POST,
  ADD_MESSAGE,
  UPDATE_NEW_POST_TEXT,
  UPDATE_NEW_MESSAGE_BODY,
  TOGGLE_POST_LIKE,
  FOLLOW,
  UNFOLLOW,
  SET_USERS,
  SET_TOTAL_USERS_COUNT,
  SET_CURRENT_PAGE,
  SET_FETCHING_STATE,
  SET_USER_PROFILE,
  SET_PROFILE_FETCHING_STATE,
  TOGGLE_IS_FOLLOWING_PROGRESS,
  SET_STATUS,
  SET_PROFILE_PHOTO,
  SET_PROFILE_DATA,
};
